language: rust

sudo: required

matrix:
  include:
    - rust: 1.20.0
    - rust: stable
    - rust: beta
    - rust: nightly

branches:
  only:
    - master

script:
  - |
      cargo test --verbose &&
      cargo build --verbose &&
      cargo build --verbose --no-default-features &&
      cargo build --release --verbose &&
      cargo build --release --verbose --no-default-features
